create table users
(
    id       bigint generated by default as identity
        constraint users_pkey
            primary key,
    name     varchar(255),
    password varchar(255),
    username varchar(255)
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
);
insert into users (name, password, username)
values ('Admin', 'admin', 'admin'),
       ('Diyas', 'qwerty', 'diyas'),
       ('User', 'user', 'user');